version: '3'
services:

  # Database - MariaDB has been chosen, runs on default port
  db:
    container_name: database
    image: mariadb
    volumes:
      - ./db_data/:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - backend

  # Wordpress - FPM-Alpine default port 9000
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    container_name: wordpress
    restart: always
    volumes: ["./www/:/var/www/html","./upload.ini:/usr/local/etc/php/conf.d/uploads.ini"]
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_REDIS_HOST', 'redis');
    networks:
      - frontend
      - backend

  # Caddy Web Server
  caddy:
    image: caddy
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www:/var/www/html
      - ./caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - frontend

  # phpmyadmin - allows simple db migration, runs on port 8788
  phpmyadmin:
    depends_on:
      - db
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8788:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 512M
    networks:
      - frontend
      - backend

  # redis - cache for Wordpress
  redis:
    image: 'redis:alpine'
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    restart: always
    expose:
      - '6379'
    networks:
      - frontend

networks:
  frontend:
  backend:
    internal: true
volumes:
  db_data:
  www:
  caddy_data:
  redis:
